### ISSUE TITLE
关于pc版

### ISSUE THREAD

**Issue by xiw249** [MahotsukaiCN/mahotsukaicn.github.io#2]
我想问下原版补丁或者是该补丁是否可以用在最近才出的steam版上，如果不能的话是否有出steam版补丁的打算

**Comment by letdo1945** [comment]
steam版补丁请移步http://tieba.baidu.com/p/8831682503?share=9105&fr=share&see_lz=0&sfc=copy&client_type=2&client_version=11.7.8.1&st=1703900203&unique=64F91F647AA34B848E7B7BC3DE2DE9CB
